### ISSUE TITLE
3.9 As a gamer, I want to get information about points for each round. 

### ISSUE THREAD

**Issue by binxxxxx** [sopra-fs24-group-18/sopra-fs24-group-18-server#102]
## Acceptance Criteria: 
- [ ] In each round, after all the players select the price, the page will show the game prompts.
- [ ] The game prompts inform the player of the points earned, and I can click the Confirm button to close it. 
- [ ] The current game points displayed in the upper right corner of the page will be updated automatically.

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#104
#### Subtasks:
- [ ] Query the database to retrieve information about points earned in each round of the game.
- [ ] Format the points information into data suitable for display on the client side.

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#57
#### Subtasks:
- [ ] Update the user's points in the database based on information about points earned in each round of the game.

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-client#43
#### Subtasks:
- [ ] Create a popup window to display game prompt information and points earned.
- [ ] Include a confirm button in the popup window to close it.

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-client#44
#### Subtasks:
- [ ] Call the server-side endpoint to retrieve information about points earned in the game.
- [ ] Display the retrieved points information in the game prompt popup window.

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#45
#### Subtasks:
- [ ] Call the server-side endpoint to retrieve the latest user points information.
- [ ] Display the retrieved points information in the top right corner of the page.

**Comment by YanYang-G0001** [comment]
9d65fbfd33f8196861ebf0b881f3505f750f4ceb
