### ISSUE TITLE
3.10 As a gamer, I can use points to exchange for props after each round during the game.

### ISSUE THREAD

**Issue by binxxxxx** [sopra-fs24-group-18/sopra-fs24-group-18-server#109]
## Acceptance Criteria: 
- [ ] After I click the Confirm button to close game prompts after each round, I will automaticly be navigated to the props shop. 
- [ ] A window of shop appears on the page showing the points needed to redeem the item and the points I have. 
- [ ] After clicking on the Redeem button, if I don't have enough points, a prompt will appear.
- [ ] If the exchange is successful, the exchange window will close, the number of items will be increased by 1, and the number of points will be decreased. 

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#110
#### Subtasks:
- [ ] Retrieve information about available props and their corresponding point costs from the database.
- [ ] Format the prop shop information into data suitable for display on the client side.

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#111
#### Subtasks:
- [ ] Validate user's points and check if they have enough points to redeem the desired prop.
- [ ] Update user's points in the database upon successful redemption.
- [ ] Update user's props in the database upon successful redemption.

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#46
#### Subtasks:
- [ ] Create a window on the page to display the prop shop, showing the points needed to redeem each item and the user's current points. 
- [ ] Include a redeem button for each item in the prop shop.

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#47
#### Subtasks:
- [ ] Handle user clicks on the redeem button and send redemption requests to the server.
- [ ] Display a prompt if the user does not have enough points for redemption.

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#48
#### Subtasks:
- [ ] Update the display of user points. 
- [ ] Update the display of the number of items.
