### ISSUE TITLE
3.11 As a gamer, I can use the redeemed props during gameplay.

### ISSUE THREAD

**Issue by binxxxxx** [sopra-fs24-group-18/sopra-fs24-group-18-server#115]
## Acceptance Criteria: 
- [ ] Click on the props button in the upper right corner, if the number of props is 0, there is no response. 
- [ ] If the use of props is successful, a reminder window will appear on the page and the number of props will be reduced by 1. 

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#116
#### Subtasks:
- [ ] Validate the request to ensure the user has the necessary props available.

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#117
#### Subtasks:
- [ ] Update the user's inventory in the database to reflect the use of the prop.
- [ ] Ensure that the number of props is reduced by 1 upon successful use.

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#49
#### Subtasks:
- [ ] Create a button in the upper right corner of the page to access the props menu.
- [ ] Display the number of props available next to the button. 

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#50
#### Subtasks:
- [ ] Handle user clicks on the props button and send requests to the server to use props.
- [ ] Display a reminder window on the page if the use of props is successful.
