### ISSUE TITLE
3.3 As a player, after I start the price guessing game, I want to see the game interface. (Price Guessing Mode)

### ISSUE THREAD

**Issue by Unusz** [sopra-fs24-group-18/sopra-fs24-group-18-server#53]
## Acceptance Criteria: 
- [ ] In each round, an item picture along with its name would be shown on the players’ screen. 
- [ ] Beside the picture, there is a slider representing the range of the item's price. Users can adjust the slider to guess the item’s price. 
- [ ] On the top right corner, there is a countdown timer. Each round lasts 30 seconds. 
- [ ] Optional: Next to the item picture, players can click on the '+' and '-' magnifying glass icons to zoom in and out of the picture for a closer examination. 

Priority: High
Estimated Time: 6-8 hours 

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-server#54
#### Subtasks:
- [ ] Generate questions for the game room when the game start.
- [ ] Send the item’s picture, price range information to the front end by round.
Time Estimate: 6 hours

#### Task: 
- [ ] #132
#### Subtasks:
- [ ] Retrieve item picture and price from ebay
Time Estimate: 8 hours

#### Task: 
- [ ] #133
#### Subtasks:
- [ ] Retrieve certain amount of item data and save it into the database when the server starts.
Time Estimate: 6 hours

#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#53
#### Subtasks:
- [ ] Send request to back end to get an item’s information.
- [ ] Display the item picture on the left side of the interface.
- [ ] Place an slider on the right side of the image.
- [ ] Based on the price range returned by the backend, display the corresponding numbers at the left and right ends of the slider.

Time Estimate: 4 hours
