### ISSUE TITLE
3.4 As a player, after I start the game, I want to see the game interface. (Budget Mode)

### ISSUE THREAD

**Issue by Unusz** [sopra-fs24-group-18/sopra-fs24-group-18-server#57]
## Acceptance Criteria: 
- [ ] In each round, a 3*3 grids would be shown, each cell filled with an item picture.
- [ ] Users can select one or multiple cells, after selection, a “√” would be shown on the corner of the item picture, representing this item has been chosen.

Priority: High
Estimated Time: 3-4 hours 

#### Task: 
- [ ] For budget mode, implement an endpoint to return a list of items’ picture and name information to the front end.
#### Subtasks:
- [ ] Retrieve item information from an external API.
- [ ] Save item information in a list.
- [ ] send the item’s information list to the front end.

Time Estimate: 3 hours

#### Task: 
- [ ] 3.4.2 Design the user interface for displaying the items information.
### Subtasks:
- [ ] Send request to back end to get a list of items.
- [ ] Draw a 3*3 grid at the center, within each cell, an item picture is displayed.

Time Estimate: 3 hours
