### ISSUE TITLE
3.8 As a player, I want to select one or multiple products so that the total price of these products is closest to the given budget.

### ISSUE THREAD

**Issue by Unusz** [sopra-fs24-group-18/sopra-fs24-group-18-server#61]
## Acceptance Criteria: 
- [ ] In each round, players are given one attempt to select the products.
- [ ] Within one attempt, the player should select one or multiple products to let the total price of these products be closest to the budget.
- [ ] After selection, players should confirm and submit their answers.

Priority: High
Estimated Time: 6-8 hours 

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#62
#### Subtasks:
- [ ] Receive a list of selected product ids from the client-side.
- [ ] Calculate the total price of these selected products.
- [ ] After receiving all players' answers and calculating the total price, rank the players. The closer the total price of the selected products is to the budget, the higher the ranking.

Time Estimate: 5 hours

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-client#52
#### Subtasks:
- [ ] Enhance Item Display Interface: When the user clicks on an item’s picture, there needs to be some sign showing this item has been selected.
- [ ] Enhance Item Display Interface: Incorporate a "Confirm" button within the existing item display interface for submitting the list of selected items.
- [ ] Implement Confirmation Modal: Develop a confirmation message modal triggered upon clicking the "Confirm" button.
- [ ] Display the message "Are you sure you want to submit?" within the modal.
- [ ] Include "Submit" and "Cancel" buttons within the modal for user interaction.
- [ ] Handle User Actions: If the user clicks the "Submit" button, transfer the selected item list to the server for processing. If the user clicks the "Cancel" button, return the user to the item display interface.

Time Estimate: 4 hours

**Comment by YanYang-G0001** [comment]
9d65fbfd33f8196861ebf0b881f3505f750f4ceb
