### ISSUE TITLE
2.1 Create a game room, which supports users to choose mode and number of players, and also invite other users to my room. 

### ISSUE THREAD

**Issue by YanYang-G0001** [sopra-fs24-group-18/sopra-fs24-group-18-server#65]
## Acceptance Criteria:

- [ ] As a user, I want to have the option to create a new game room from the homepage.
- [ ] As a user, I want to specify the room name when creating a game room.
- [ ] As a user, I want to choose the game mode and number of players for the game room.
- [ ] As a user, I want to share the link of the game room with other users.
- [ ] As a user, I want the created room to be accessible to other users via a link and to start a game within the entered range of players.

Priority: Medium  
Estimated Time: 12-20 hours  

#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#80
#### Subtasks:
- [ ] Validate user authentication.
- [ ] Generate a unique identifier for the new game room.
- [ ] Include input field for room name in the creation form.
- [ ] Store room details in the database.
#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#81
#### Subtasks:
- [ ] Include dropdown or radio buttons for selecting game mode.
- [ ] Include a dropdown for selecting the number of players.
#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#82
#### Subtasks:
- [ ] Create a unique URL that includes the room identifier.
#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#83
#### Subtasks:
- [ ] Redirect users to the newly created room after creation.
- [ ] Start the game when the required number of players have joined.
#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#31
#### Subtasks:
- [ ] Create form elements for specifying room name, game mode, and number of players.
#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#32
#### Subtasks:
- [ ] Add validation for the room name input.
#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#33
#### Task: 
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-client#34
#### Subtasks:
- [ ] Display the link to the user after room creation.
#### Task: 
- [x] sopra-fs24-group-18/sopra-fs24-group-18-client#35
#### Subtasks:
- [ ] Redirect users to the room page upon creation.
#### Time Estimate: 1 hour
